/* ──────────────────────────────────────────────────────────────
   JUNGLE BACKGROUND — ShaderToy (single pass, no backbuffers)

   Whole-screen storm of LEAVES swaying down the frame, over your
   own background. The leaf itself is generated by the shader — the
   exact 3D leaf from the reference: an sdLeave silhouette WRAPPED
   ON A SPHERE (leaveSphere), so each leaf curls and shows its
   face/back as it tumbles, instead of being a flat cut-out.

   • DEPTH PARALLAX: leaves span front-to-back; near leaves are
     bigger and fall/drift faster. Near occludes far.
   • VARIABLE WIND: a steady drift plus surging GUSTS heave the
     whole field sideways in slow waves (not a constant slide).
   • Each leaf ROCKS like a real falling leaf — a pendulum sway
     that swings it side-to-side AND tilts it, on its own clock —
     on top of a shared 3D TUMBLE. Per-leaf size / colour / phase
     so none match.

   No screen post-effects — just leaves over the background.
   (No glare, fog, tonemap, saturation, grade, vignette or dither.)

   Paste the whole file into shadertoy.com/new and hit Alt+Enter.

   iChannel0: YOUR BACKGROUND image/video (shows through the gaps
   between leaves). Leave it empty and it previews on a procedural
   sky gradient.

   Reference leaf generator (sdLeave / leaveSphere / sphIntersect /
   polar / the hash1/2/3 RNG) is kept VERBATIM from the user's code
   so the leaf shape and tumble match exactly. Everything around it
   is the tunable control panel: parallax, wind, gusts, sway,
   colour, background.

   EVERY knob lives in the TUNABLES block. The body is prose.
   ────────────────────────────────────────────────────────────── */

#define time iTime
#define PI 3.141592
#define TAU 6.283185

// ═══════════════════════════════════════════════════════════════
// TUNABLES
// ═══════════════════════════════════════════════════════════════
// Comments name the ENDPOINTS — which way to push, what you see.

// ── Population & spread ────────────────────────────────────────
#define LEAF_COUNT 150  // leaves in the field, drawn back-to-front. RAISE when CAM_DIST is high (bigger field => sparser)

const float FIELD_OVERFILL = 1.15;  // field size vs the view. 1.0 = fills exactly to the edges,
                                    // >1 = leaves spawn/exit past the edges (no visible boundary),
                                    // <1 = empty bands at the sides. The field auto-fits the camera,
                                    // so raising CAM_DIST no longer leaves the sides bare.
const float TIME_SCALE = 1.0;  // master tempo: 0.5 = slow-mo, 2.0 = frantic

// ── Fall (downward drift) ──────────────────────────────────────
const float FALL_BASE = 0.05;       // base fall speed (field-heights/sec). raise = heavier rain of leaves
const float FALL_PARALLAX = 0.9;    // extra fall speed on NEAR leaves vs far (0 = all fall the same)

// ── Wind (steady drift + surging gusts = the "variable wind") ──
const float WIND_DRIFT = -0.05;     // steady sideways push (sign = direction; 0 = straight down)
const float WIND_PARALLAX = 1.0;    // extra wind on near leaves vs far (0 = uniform sideways)
const float WIND_GUST = 0.01;       // GUST strength — extra sideways heave that surges in and out
const float WIND_GUST_RATE = 0.02;  // gust frequency — low = long slow heaves, high = choppy

// ── 3D tumble (shared spin of the whole field) ─────────────────
const vec2 SPIN_RATE = vec2(0.20, 0.30);  // base tumble speed (x-spin, y-spin). 0 = leaves frozen flat
const float SPIN_DESYNC = 1.0;            // per-leaf random tumble offset (0 = all aligned, 1 = full scatter)

// ── Per-leaf ROCK (pendulum sway of a real falling leaf) ───────
// One clock per leaf drives BOTH the sideways swing and the tilt.
const float SWAY_AMP = 0.35;        // side-to-side swing width (field units; 0 = falls straight)
const float SWAY_TILT = 0.45;       // how much the leaf tilts as it swings (rad; 0 = no rocking)
const float SWAY_RATE_MIN = 0.5;    // slowest rockers (leaves that sway lazily)
const float SWAY_RATE_MAX = 1.6;    // fastest rockers (leaves that flutter quickly)

// ── Leaf size (per-leaf range) ─────────────────────────────────
const float LEAF_RA_MIN = 0.3;  // smallest leaf radius (distant/tiny)
const float LEAF_RA_VAR = 0.8;  // added on top of MIN by random roll => max = MIN+VAR

// ── Leaf colour (jungle green; per-leaf shade between DARK and LIGHT) ─
// Each leaf rolls a random 0..1 and mixes DARK->LIGHT, so the swarm spans
// the whole range. Collapse DARK == LIGHT for one flat colour.
const vec3 LEAF_COL_DARK = vec3(0.05, 0.22, 0.03);   // darkest leaf (deep shade green). raise for a brighter floor
const vec3 LEAF_COL_LIGHT = vec3(0.45, 0.80, 0.18);  // lightest leaf (sun-lit lime). push g = more vivid, add r/b = paler
const float LEAF_HUE_JITTER = 0.12;  // per-leaf warm/cool wander (0 = uniform, 0.3 = red/yellow strays)
const float LEAF_BRIGHT = 1.0;       // overall canopy gain. <1 darker, >1 punchier
const float FAR_FADE = 0.40;         // haze dimming on far leaves (0 = none, 1 = far ~black)

// ── Camera ─────────────────────────────────────────────────────
const float CAM_DIST = 15.0;   // how far back the eye sits (bigger = leaves smaller / wider field)
const float CAM_FOV = 1.5;     // lens: LOW = wide/strong perspective, HIGH = tele/flatter
const float LEAF_ZBACK = 8.0;  // depth of the FARTHEST leaves (bigger = deeper cloud, more parallax)

// ── Background (iChannel0, seen through the gaps) ───────────────
const float BG_BRIGHT = 1.0;  // gain on the bound background. <1 dims, >1 lifts
const vec3 BG_SKY_LO = vec3(0.20, 0.26, 0.30);  // fallback sky at bottom (no texture bound)
const vec3 BG_SKY_HI = vec3(0.45, 0.52, 0.55);  // fallback sky at top

// ═══════════════════════════════════════════════════════════════
// LEAF GENERATOR — kept VERBATIM from the reference (the "leaf image")
// ═══════════════════════════════════════════════════════════════

mat2 rot(float a)
{
    float s = sin(a), c = cos(a);
    return mat2(c, -s, s, c);
}

float hash21(vec2 p)
{
    p = fract(p * vec2(452.127, 932.618));
    p += dot(p, p + 123.23);
    return fract(p.x * p.y);
}

float noise(vec2 p)
{
    vec2 q = floor(p);
    vec2 f = fract(p);
    f = f * f * (3.0 - 2.0 * f);
    return mix(mix(hash21(q + vec2(0, 0)), hash21(q + vec2(1, 0)), f.x),
               mix(hash21(q + vec2(0, 1)), hash21(q + vec2(1, 1)), f.x), f.y);
}

float fbm(vec2 p)
{
    float f = 0.0;
    f += 0.5 * noise(p);
    f += 0.25 * noise(p * 2.0);
    f += 0.125 * noise(p * 4.0);
    f += 0.0625 * noise(p * 8.0);
    return f;
}

// leaf silhouette SDF (blade + two side-lobes + stem)
float sdLeave(vec2 p)
{
    float d = length(p * vec2(1, 0.9) - vec2(0, 0.02)) - 0.2 + 0.9 * abs(p.x);
    p.x = abs(p.x);
    vec2 q = p;
    q -= vec2(0, -0.2 + 32.0 * pow(p.x, 5.0));
    q *= rot(PI * 0.3 + 0.1 * fbm(16.0 * p));
    q -= vec2(0, 0.17);
    d = min(d, length(q) - 0.17 + 2.0 * abs(q.x));
    q = p;
    q -= vec2(-0.07, -0.1 + 6.0 * pow(p.x, 3.0));
    q *= rot(PI * 0.7 + 0.1 * fbm(24.0 * p));
    q -= vec2(0, 0.13);
    d = min(d, length(q) - 0.13 + 2.5 * abs(q.x));
    q = p;
    // stem
    float h = clamp(q.y, -0.377, 0.0);
    q -= vec2(0, h);
    d = min(d + 0.2 * pow(fbm(24.0 * p), 3.0), length(q) + 0.02 * h);
    return d;
}

// ray-sphere intersection (iq: https://iquilezles.org/articles/intersectors/)
vec2 sphIntersect(vec3 ro, vec3 rd, vec3 ce, float ra)
{
    vec3 oc = ro - ce;
    float b = dot(oc, rd);
    float c = dot(oc, oc) - ra * ra;
    float h = b * b - c;
    if (h < 0.0) return vec2(-1);
    h = sqrt(h);
    return vec2(-b - h, -b + h);
}

vec2 polar(vec3 p)
{
    return vec2(atan(p.x, p.z), p.y);
}

// leaf wrapped on a sphere -> alpha coverage for this ray
float leaveSphere(vec3 ro, vec3 rd, vec3 ce, vec2 an, float ra)
{
    vec2 t = sphIntersect(ro, rd, ce, ra);
    if (t.y < 0.0) return 0.0;  // no intersection
    vec3 oc = ro - ce;
    vec3 p = oc + rd * t.x;  // front point
    vec3 q = oc + rd * t.y;  // back point
    p.xz *= rot(an.x);
    q.xz *= rot(an.x);
    p.yz *= rot(an.y);
    q.yz *= rot(an.y);
    float di = ra * 2.0;  // diameter
    vec2 r = vec2(ra, 1) / di;  // ratio
    vec2 pf = polar(p) * r;  // polar front point
    vec2 pb = polar(q) * r;  // polar back point
    float lf = step(sdLeave(pf), 0.0);  // front face inside leaf?
    float lb = step(sdLeave(pb), 0.0);  // back face inside leaf?
    return lf * (1.0 - lb) + lb;  // coverage
}

// per-leaf RNG (each call advances the seed once) — verbatim
float hash1(inout float n) { return fract(sin(n += 1.0) * 2348.3241); }
vec2  hash2(inout float n) { return fract(sin(n += 1.0) * vec2(2348.3241, 4591.5392)); }
vec3  hash3(inout float n) { return fract(sin(n += 1.0) * vec3(2348.3241, 4591.5392, 3412.4231)); }

// ═══════════════════════════════════════════════════════════════
// RENDER
// ═══════════════════════════════════════════════════════════════

vec3 render(vec3 ro, vec3 rd, vec3 bg)
{
    vec3 col = bg;  // background shows through the gaps
    float t = time * TIME_SCALE;

    // Surging gust shared by all leaves (two desynced sines -> non-repeating heave)
    float gust = WIND_GUST * (0.6 * sin(t * WIND_GUST_RATE) + 0.4 * sin(t * WIND_GUST_RATE * 2.3 + 1.7));

    // Field box AUTO-SIZED to overfill the frustum at the deepest leaf plane, so
    // leaves always reach past the screen edges (no abrupt side cutoff) for any
    // CAM_DIST / CAM_FOV / aspect. The deepest plane governs => nearer planes
    // spill safely off-screen. halfV is the world half-height at that plane.
    float aspect = iResolution.x / iResolution.y;
    float halfV = (CAM_DIST + LEAF_ZBACK) * 0.5 / CAM_FOV;
    vec2 field = vec2(halfV * aspect, halfV) * 2.0 * FIELD_OVERFILL;

    vec2 an = t * SPIN_RATE;  // global field tumble

    for (float i = 0.0; i < 1.0; i += 1.0 / float(LEAF_COUNT)) {
        float n = i + 1.0;  // random seed for this leaf
        float depth = i;    // 0 far .. 1 near (near drawn last => on top)

        // ── Motion: fall + steady wind + gust, with near faster (parallax) ──
        vec2 rnd2 = hash2(n);  // this leaf's home cell
        float par = 1.0 + WIND_PARALLAX * depth;
        vec2 move = vec2((WIND_DRIFT * par) + gust * (0.3 + depth),
                         FALL_BASE * (1.0 + FALL_PARALLAX * depth)) * t;
        vec2 p = (0.5 - fract(rnd2 + move)) * field;

        // ── 3D tumble desync (mutates the shared accumulator, like the ref) ──
        an += (hash1(n) - 0.5) * SPIN_DESYNC;

        // ── Colour: jungle green, per-leaf shade + gentle hue wander ──
        vec3 rnd = hash3(n);
        vec3 mat = mix(LEAF_COL_DARK, LEAF_COL_LIGHT, rnd.x);
        mat.r += (rnd.y - 0.5) * LEAF_HUE_JITTER;
        mat.g += (rnd.z - 0.5) * LEAF_HUE_JITTER * 0.5;
        mat = clamp(mat * LEAF_BRIGHT, 0.0, 1.0);
        mat *= mix(1.0 - FAR_FADE, 1.0, depth);  // atmospheric dimming of far leaves

        float ra = LEAF_RA_MIN + LEAF_RA_VAR * hash1(n);  // per-leaf radius

        // ── ROCK: pendulum sway on its own clock — swing x AND tilt together ──
        float swayRate = mix(SWAY_RATE_MIN, SWAY_RATE_MAX, hash1(n));
        float swayPhase = t * swayRate + hash1(n) * TAU;
        p.x += SWAY_AMP * sin(swayPhase);
        vec2 anLeaf = an + vec2(SWAY_TILT * sin(swayPhase + PI * 0.5), 0.0);

        vec3 ce = vec3(p, LEAF_ZBACK * (1.0 - i));  // depth: first leaves far, last near
        float alpha = leaveSphere(ro, rd, ce, PI * anLeaf, ra);
        col = mix(col, mat, alpha);  // alpha-over: near hides far
    }

    return col;
}

// ═══════════════════════════════════════════════════════════════
// MAIN IMAGE
// ═══════════════════════════════════════════════════════════════

void mainImage(out vec4 fragColor, in vec2 fragCoord)
{
    // Ray for this pixel (aspect-correct: divide by .y)
    vec2 pc = (fragCoord - 0.5 * iResolution.xy) / iResolution.y;
    vec3 ro = vec3(0.0, 0.0, -CAM_DIST);
    vec3 rd = normalize(vec3(pc * CAM_FOV, 1.0));

    // background from iChannel0, with a procedural sky fallback so it
    // previews without a texture bound
    vec2 uv = fragCoord / iResolution.xy;
    vec3 tex = texture(iChannel0, uv).rgb;
    float hasTex = step(0.01, dot(tex, vec3(1.0)));
    vec3 bg = mix(mix(BG_SKY_LO, BG_SKY_HI, uv.y), tex, hasTex) * BG_BRIGHT;

    vec3 col = render(ro, rd, bg);
    fragColor = vec4(col, 1.0);
}
